version: "3.1"

networks:
  net1:

services:
  db:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: app
      POSTGRES_DB: app_3
    ports:
      - "5431:5432"
    networks:
      net1:
        aliases:
          - database